name: money_tracker

packages:
  - modules/*

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  gen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      flutter: true

  gen:intl:
    exec: dart run intl_utils:generate
    packageFilters:
      flutter: true
