name: optimize
description: "Project & Task Management Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

workspace:
  - modules/core
  - modules/auth

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ./modules/core
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/

melos:
  command:
    bootstrap:
      runPubGetInParallel: true

  scripts:
    gen:
      exec: dart run build_runner build --delete-conflicting-outputs
      packageFilters:
        flutter: true

    gen:intl:
      run: dart run core:merge_l10n
      exec:
        concurrency: 1
      packageFilters:
        flutter: true
