name: auth
description: "Authentication module for Optimize application"
version: 0.0.1
resolution: workspace
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_form_builder: ^10.2.0
  flutter_hooks: ^0.21.3+1
  go_router: ^16.2.1
  flutter_svg: ^2.2.1
  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.11

flutter_intl:
  enabled: true
  main_locale: th
  class_name: AuthLocalizations
  arb_dir: lib/src/view/l10n
  output_dir: lib/gen
