name: auth
description: "Authentication module for Optimize application"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.11

flutter:

flutter_intl:
  enabled: true
  main_locale: th
  class_name: AuthLocalizations
  arb_dir: lib/src/view/l10n
  output_dir: lib/gen
