name: core
description: "Core module for Optimize application"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.3.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  ua_client_hints: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  hive_ce_generator: ^1.9.3
  flutter_gen_runner: ^5.11.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  fonts:
    - family: LineSeedSansTH
      fonts:
        - asset: ./assets/fonts/LINESeedSansTH_A_Rg.ttf
          weight: 400
        - asset: ./assets/fonts/LINESeedSansTH_A_Bd.ttf
          weight: 500

flutter_gen:
  output: ./lib/gen
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: Assets
